from django.conf.urls.defaults import patterns, include, url
import settings

urlpatterns = patterns('',
    url(r'^jsi18n/$',
        'django.views.i18n.javascript_catalog',
        {'packages': settings.INSTALLED_APPS, 'domain' : 'django'},
        name = 'i18n-js-catalog'),
    url(r'^accounts/login/$',
        'karteikarten.login.login',
        name = 'login'),
    url(r'^accounts/logout/$',
        'karteikarten.login.logout',
        name = 'logout'),
    url(r'^accounts/register/$',
        'karteikarten.login.register',
        name = 'register'),
    url(r'^accounts/recover_password/$',
        'karteikarten.login.recoverPassword',
        name = 'recover-password'),
    url(r'^accounts/recover_password/reset/$',
        'karteikarten.login.recoverResetPassword',
        name = 'recover-reset-password'),
    url(r'^$',
        'karteikarten.centre.centre',
        name = 'centre'),
    url(r'^documentation/$',
        'karteikarten.centre.documentation',
        name = 'documentation'),
    url(r'^run/$',
        'karteikarten.centre.selectRunOptions',
        name = 'select-run-options'),
    url(r'^run/review/(?P<set_id>\d+)/$',
        'karteikarten.run.run',
        name = 'run-run'),
    url(r'^run/finished/$',
        'karteikarten.run.finished',
        name = 'run-finished'),
    url(r'^edit/$',
        'karteikarten.centre.selectSetToEdit',
        name = 'select-set-to-edit'),
    url(r'^edit/new/$',
        'karteikarten.edit.newSet',
        name = 'new-set'),
    url(r'^edit/(?P<set_id>\d+)/$',
        'karteikarten.edit.editSet',
        name = 'edit-set'),
    url(r'^edit/(?P<set_id>\d+)/delete/$',
        'karteikarten.edit.deleteSet',
        name = 'delete-set'),
    url(r'^edit/(?P<set_id>\d+)/boxes/$',
        'karteikarten.edit.viewBoxesBySet',
        name = 'edit-view-boxes-by-set'),
    url(r'^edit/(?P<set_id>\d+)/boxes/new/$',
        'karteikarten.edit.newBox',
        name = 'new-box'),
    url(r'^edit/(?P<set_id>\d+)/boxes/(?P<box_id>\d+)/$',
        'karteikarten.edit.editBox',
        name = 'edit-box'),
    url(r'^edit/(?P<set_id>\d+)/boxes/(?P<box_id>\d+)/delete/$',
        'karteikarten.edit.deleteBox',
        name = 'delete-box'),
    url(r'^edit/(?P<set_id>\d+)/cards/$',
        'karteikarten.edit.viewCardsBySet',
        name = 'edit-view-cards-by-set'),
    url(r'^edit/(?P<set_id>\d+)/cards/new/$',
        'karteikarten.edit.newCard',
        name = 'new-card'),
    url(r'^edit/(?P<set_id>\d+)/cards/(?P<card_id>\d+)/$',
        'karteikarten.edit.editCard',
        name = 'edit-card'),
    url(r'^edit/(?P<set_id>\d+)/cards/(?P<card_id>\d+)/delete/$',
        'karteikarten.edit.deleteCard',
        name = 'delete-card'),
    url(r'^edit/(?P<set_id>\d+)/import/$',
        'karteikarten.edit.setImport',
        name = 'set-import'),
    url(r'^edit/(?P<set_id>\d+)/export/$',
        'karteikarten.edit.setExport',
        name = 'set-export'),
    url(r'^settings/$',
        'karteikarten.settings.settings',
        name = 'settings'),
    url(r'^settings/user_info/$',
        'karteikarten.settings.changeUserInformation',
        name = 'settings-change-user-information'),
    url(r'^ajax/$',
        'karteikarten.ajax.ajax',
        name = 'ajax'),
    url(r'^mobile/$',
        'karteikarten.mobile.mobile',
        name = 'mobile'),
    url(r'^mobile/cache_manifest/$',
        'karteikarten.mobile.cacheManifest',
        name = 'mobile-cache-manifest'),
  )
